config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :prizes, except: :show
  resources :settings, only: [:create, :update, :index]

  resources :users, only: [:index, :create, :show, :destroy] do
	resources :shares, only: [] do
	  collection do 
	    get "/" => "shares#create"
	  end
	end
  end

  root "users#new"
  get "privacy" => "pages#privacy"


end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :referrer, class_name: "User", foreign_key: :referrer_id
    has_many :referrals, class_name: "User", foreign_key: :referrer_id
    has_many :shares

    validates :email, uniqueness: true, format: { with: Devise::email_regexp, message: "Invalid email format." }, presence: true
    validates :ip_address, presence: true, uniqueness: true

    before_create :set_referral_code
    after_create :add_user_to_mailchimp
    after_create :welcome_email
    after_create :referral_email

    def prize
    	Prize.where(number_of_referrals: 0..number_of_referrals).order("number_of_referrals asc").last
    end

    def progress
        unit = prize ? 1.fdiv(Prize.all.count) :1.fdiv(2 * Prize.all.count)
        targets = Prize.all.order("number_of_referrals asc").pluck(:number_of_referrals)
        base = 0

        unless prize
            return unit * (number_of_referrals.fdiv(targets[0]))
        end

        targets.each_with_index do |value, index|
            if number_of_referrals >= value && value > 0
                base += unit
            elsif index > 0
                base += unit * (number_of_referrals - targets[index - 1]).fdiv(value - targets[index - 1])
                break
            end
        end

        base -= unit.fdiv(2)

        return base
    end

    def achieved prize
        prize.number_of_referrals <= number_of_referrals
    end


    def prize_name
        prize ? prize.name : nil
    end

    def number_of_referrals
        referrals.count
    end

    def social_url(social_network)
        "/users/#{referral_code}/shares?share%5Bsocial_network%5D=#{social_network}"
    end

    def user_url(root_url)
        root_url + "users/" + referral_code
    end

    def referral_url(root_url)
        root_url + "?ref=" + referral_code
    end

    def self.as_csv
        attributes = [:id, :created_at, :email, :ip_address, :referrer_id, :referral_code, :number_of_referrals, :prize_name]

        CSV.generate do |csv|
            csv << attributes
            all.each do |item|
                raw = []
                attributes.each do |attribute|
                    raw << item.send(attribute)
                end
                csv << raw
            end
        end
    end

    private

    def mailchimp_object
        Gibbon::Request.new(api_key: Setting::MAILCHIMP_API_KEY)
    end

    def add_user_to_mailchimp
        delay.mailchimp_subscribe if Setting::MAILCHIMP_API_KEY.presence && Setting::MAILCHIMP_LIST_ID.presence
    end

    def mailchimp_subscribe
        begin
            contact = mailchimp_object.lists(Setting::MAILCHIMP_LIST_ID).members.create(body: {email_address: email, status: "subscribed"})
        rescue Gibbon::MailChimpError => ex
            print ex.body
        end
    end


    def set_referral_code
    	self.referral_code = generate_referral_code
    end

    def generate_referral_code
	    loop do
	      code = SecureRandom.hex(5)
	      break code unless self.class.where(referral_code: code).exists?
	    end
    end

    def welcome_email
        UserMailer.delay.sign_up_email(self)
    end

    def referral_email
        UserMailer.delay.referral_email(User.find(referrer_id)) if referrer_id
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :retrive_referrer, only: :new
	before_action :check_session, only: :new
	before_action :check_email_address, only: :create
	before_action :fetch_user, only: [:show, :destroy]
	before_action :authenticate_admin, only: [:index, :destroy]


	def index
		@users = User.all.order("created_at desc").paginate(:page => params[:page], :per_page => 100)

		respond_to do |format|
	    	format.html {render layout: "dashboard"}
	    	format.csv { send_data User.all.as_csv }
    	end 
	end

	def destroy
		if @user.destroy
			redirect_to users_path, notice: "User has been successfully deleted."
		else
			redirect_to users_path, alert: "User hasn't been deleted."
		end
	end


	def new
		@user = User.new
		respond_to do |format|
            format.html
        end
	end

	def show
		respond_to do |format|
            format.html
        end
	end



	def create

		@user = User.new(user_params)
		@user.referrer_id = session[:referrer_id] if session[:referrer_id].present?
		@user.ip_address = request.ip

		if @user.save
			cookies[:user_id] = @user.id
			respond_to do |format|
	            format.html {redirect_to user_path(@user.referral_code), notice: "Thank you for signing up."}
	        end
	    else
			respond_to do |format|
	            format.html {redirect_to root_path, alert: "Subscribing multiple emails is not allowed."}
	        end
	    end
	end


	private 


	def check_session
		if cookies[:user_id] && User.where(id: cookies[:user_id]).any? && !current_admin
			redirect_to user_path(User.find(cookies[:user_id]).referral_code)
		end
	end

	def check_email_address
		if params[:user] && User.where(email: params[:user][:email]).any?
			redirect_to user_path(User.find_by(email: params[:user][:email]).referral_code)
		end
	end

	def retrive_referrer
		if params[:ref] && User.where(referral_code: params[:ref]).any?
			session[:referrer_id] = User.find_by(referral_code: params[:ref]).id
		end
	end

	def fetch_user
		@user = User.find_by(referral_code: params[:id])
	end

	def user_params
    	params.require(:user).permit(:email)
  	end 


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user, html: {novalidate: false, class: "form-inline"} do |f|
	= f.input :email, as: :email, label: false, placeholder: "Enter Email", input_html: {required: true }
	.form-group.submit
		= f.button :submit, "STEP INSIDE", class: "btn btn-branded"

app/views/users/_social_sharing.html.haml
#social-sharing
	%ul.contact-socials.clearfix
		%li
			%a.foo_social.ico-facebook{:href => @user.social_url("facebook"), target: "_blank"}
				%i.fa.fa-facebook-official 
		%li
			%a.foo_social.ico-twitter{:href => @user.social_url("twitter"), target: "_blank"}
				%i.fa.fa-twitter
		%li
			%a.foo_social.ico-gplus{:href => @user.social_url("google_plus"), target: "_blank"}
				%i.fa.fa-google-plus

		%li
			%a.foo_social.ico-linkedin{:href => @user.social_url("linkedin"), target: "_blank"}
				%i.fa.fa-linkedin

		%li
			%a.foo_social.ico-pinterest{:href => @user.social_url("pinterest"), target: "_blank"}
				%i.fa.fa-pinterest

		%li
			%a.foo_social.ico-mail{:href => "mailto:?&subject=#{Setting.sharing[:email_subject]}&body=#{Setting.sharing[:email_message] + " " + @user.referral_url(root_url)}", target: "_blank"}
				%i.fa.fa-envelope

app/views/users/_user.html.haml
%tr
	%td= user.id
	%td= user.created_at.strftime("%B %d, %Y")
	%td= link_to user.email, user_path(user.referral_code)
	%td= user.ip_address
	%td= user.referrer_id || "No"
	%td= user.referrals.count
	%td= user.prize ? user.prize_name : "No prize"
	%td
		= link_to "Delete", user_path(user.referral_code), method: :delete, class: "btn btn-default btn-branded"

app/views/users/index.html.haml
.table-responsive
	%table.table.table-bordered.table-sorter
		%thead
			%tr
				%th ID
				%th Date
				%th Email
				%th IP address
				%th Referrer ID
				%th Referred
				%th Prize
				%th Delete

		%tbody
			= render @users

= will_paginate @users, renderer: BootstrapPagination::Rails

app/views/users/new.html.haml
-#%section#main{style: "background-image: url(#{asset_url(Setting.cover_image.url)});"}
%section#main{style: "height:446px; background-image:url(http://earlyaccess.traintogether.co/system/settings/cover_images/000/000/001/original/train-together-personal-training-software.png?1473311664);"}
  .cover{style: "text-align:left; padding-left:25px;"}
    %h1.cover-title{style: "text-align:left;"} Start Training Together
    %h3{style: "color:#373b44;"}
      Stop managing clients, start managing relationships.
      %br>/
      You deserve a better personal training software to
      %br>/
      connect with your clients. We’re here to make it

%section#section_bottom
  .wrapper{style: "text-align:center"}
    .reinforcement-statement
      #reinforcement-image{style: "height:39px; width:64px; margin-left:auto; margin-right:auto; margin-top:15px; margin-bottom:15px; background-image: url(http://prelauncher.info/system/constructors/reinforcement_icons/561a/c786/56ea/425c/c900/02a5/original/key.png?1445688053)"}
      %p.reinforcement-message{style: "font-weight:bold; text-align:center;"} ACCESS AWESOME DISCOUNTS INSIDE

    #form-wrapper
      = render "form"
    %small{style: "font-size:16px; text-align:center;"} Be the first to know, get early access

    %footer#footer{style: "margin-top:60px; margin-bottom:20px; text-align:center;"}
      %p
        Powered by
        %a{href: "http://traintogether.co", style: "font-size:14px;font-weight:bold"} Train Together, LCC

app/views/users/show.html.haml
-##refer{style: "background-image: #{Setting.additional_image.present? ? 'url(' + asset_url(Setting.additional_image.url) + ');' : 'auto'}"}
#refer{style: "padding-top:50px; margin-bottom:50px; background-size:cover; border-bottom:none; height:425px; background-image: url(http://earlyaccess.traintogether.co/system/settings/cover_images/000/000/001/original/train-together-personal-training-software.png?1473311664)"}
  .col-md-5.col-md-offset-1.col-sm-6.hidden-xs.refer-left
    .cover{style: "margin-left:auto; margin-right:auto; text-align:center"}
      %h1.cover-heading{style: "left:10px; top:145px; position:absolute; width:400px; text-align:center;"} KNOWING IS CARING
      %h4{style: "left:10px; top:200px; position:absolute; width:400px; text-align:center;"} YOUR FAMILY MATTERS THE MOST

  .col-md-5.col-sm-6.col-xs-12
    #copy
      %h3 Don't leave your friends behind
      %h1 Invite friends & Earn product

    %p{style: "color:#373b44; margin-bottom: 20px;"} Share your unique link via emails or social networks and earn prizes for each friend who signs up.
    %input.form-control{value: "#{@user.referral_url(root_url)}"}

    = render partial: "social_sharing"


%aside.text-center
  %h4
    %strong HERE'S HOW IT WORKS:

- if Prize.all.any?
  %section#prizes
    .progressbar{style: "width: #{@user.progress * 100}%"}
      .progress-box
    = render partial: "prizes/prize_item", collection: Prize.all.order("number_of_referrals asc"), as: :prize

%aside.text-center
  %h4
    %strong{style: "color:#1ABC9C;"}= pluralize(@user.number_of_referrals, 'friend')
    %span have joined so far.

%footer#footer
  %p All rights reserved
  = link_to "Privacy Policy", privacy_path, remote: true