config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :prizes, except: :show
  resources :settings, only: [:create, :update, :index]

  resources :users, only: [:index, :create, :show, :destroy] do
	resources :shares, only: [] do
	  collection do 
	    get "/" => "shares#create"
	  end
	end
  end

  root "users#new"
  get "privacy" => "pages#privacy"


end

app/views/layouts/_dashboard_sidebar.html.haml
#sidebar-header
	Admin panel

%section.sidebar-nav#users-section
	%h3
		Users
		%i.fa.fa-close
	%ul

		%li
			%a{href: "#{users_path}"} 
				All users
				%span.count= User.all.count


		%li
			%a{href: "#{users_path(format: :csv)}"} 
				Download CSV


%section.sidebar-nav#prize-parts-section
	%h3 
		Prizes
		%i.fa.fa-close
	%ul
		%li
			%a{href: "#{prizes_path}"} 
				All prizes
				%span.count= Prize.all.count

		%li
			%a{href: "#{new_prize_path}"} 
				New prize


%section.sidebar-nav#prize-parts-section
	%a{href: "#{settings_path}"} 
		%h3 
			Settings


%section.sidebar-nav
	%a{href: "#{destroy_admin_session_path}", "data-method" => "delete"}
		%h3 
			Exit

:javascript
	$(document).ready(function(){
		var selector = '#admin-sidebar [href="' + window.location.pathname + '"]';
		var item = $(selector);

		if (item.length > 0){
			item.closest("section").addClass("active");
			item.closest("li").addClass("selected");
			var title = item.closest("section").find("h3").text() + " / " +  item.contents().get(0).nodeValue
			$("#admin-content header h1").html(title);		
		}

		$(".sidebar-nav h3").on("click touchstart", function(e){

			if ($(this).parent().hasClass("active")){
				$(".sidebar-nav").removeClass("active");
			} else {
				$(".sidebar-nav").removeClass("active");
				$(this).parent().addClass("active");
			}
		});

		$(".sidebar-nav a").on("click touchstart", function(e){
			$(".sidebar-nav a").parent().removeClass("selected");
			$(this).parent().addClass("selected");
		});	
	});

app/views/layouts/_header.html.haml
- if flash[:notice]
	.alert.alert-success{role: "alert"}
		= flash[:notice]
- if flash[:alert]
	.alert.alert-danger{role: "alert"}
		= flash[:alert]
.navbar.overlay
	.container.text-center		
		%a.navbar-brand{href: "#{root_path}"}
			= image_tag("logo.png", height: 71, width: 200)

app/views/layouts/_meta.html.haml
%title Prelauncher
%meta{:content => "", :name => "Description"}/
%meta{:content => "", :name => "Keywords"}/

%link{:href => asset_path('favicon.ico'), :rel => "shortcut icon", :type => "image/x-icon"}/
%link{:href => asset_path('favicon.ico'), :rel => "apple-touch-icon", :type => "image/jpeg"}/

// Facebook
%meta{:content => "#{Setting.sharing[:facebook_title]}", :property => "og:title"}/
%meta{:content => "#{Setting.sharing[:facebook_message]}", :property => "og:description"}/

- if Setting.facebook_image.present?
	%meta{:content => root_url + Setting.facebook_image.url, :property => "og:image"}/
	%meta{:content => "570", :property => "og:image:width"}/
	%meta{:content => "300", :property => "og:image:height"}/

- if controller_name != "users"
	%meta{:content => (params[:ref] ? root_url + "users/" + params[:ref] : root_url), :property => "og:url"}/

- else
	%meta{:content => request.original_url, :property => "og:url"}/

// Google +
%meta{:content => Setting.sharing["google_plus_title"], :itemprop => "name"}/
%meta{:content => Setting.sharing["google_plus_message"], :itemprop => "description"}/
- if Setting.google_plus_image.present?
	%meta{:content => root_url + Setting.google_plus_image.url, :itemprop => "image"}/


%meta{:content => "summary_large_image", :name => "twitter:card"}/
%meta{:content => "@Prelaunchr", :name => "twitter:site"}/
%meta{:content => "Prelauncher", :name => "twitter:title"}/
%meta{:content => Setting.sharing["twitter_message"], :name => "twitter:description"}/
%meta{:content => root_url, :name => "twitter:domain"}/
- if Setting.twitter_image.present?
	%meta{:content => root_url + Setting.twitter_image.url, :name => "twitter:image"}/

%meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}

app/views/layouts/application.html.haml
!!!
%html{:itemscope => "", :itemtype => "http://schema.org/Article"}
  %head

    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = render "layouts/meta"

    :css
      #prizes .prize {width: #{100.fdiv(Prize.all.count)}%;}
      @media screen and (max-width: 767px){#prizes .prize {width: 100%;}}

  %body
    - if flash[:notice]
      .alert.alert-success{role: "alert"}
        = flash[:notice]
    - if flash[:alert]
      .alert.alert-danger{role: "alert"}
        = flash[:alert]
    %section#content-wrapper

      %main#content
        = yield

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title Admin panel
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    
  %body
    #content_wrapper
      - if flash[:notice]
        .alert.alert-success{role: "alert"}
          = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger{role: "alert"}
          = flash[:alert]
      #admin-panel
        #admin-sidebar
          = render "layouts/dashboard_sidebar"
        #admin-content
          %header
            .container-fluid   
              .row
                .col-md-12
                  %h1 Users / All
          %section
            .container-fluid
              .row
                .col-md-12  
                  = yield